/**
 * CSV Builder Unit Tests
 * Tests for tax summary CSV generation.
 */

// Mock the CsvBuilder module for Node.js testing
const CsvBuilder = (function() {
  'use strict';

  const APP_VERSION = '1.0.0';

  const CSV_HEADERS = [
    'tax_year',
    'generated_at_iso',
    'app_version',
    'informational_only',
    'filing_status',
    'state',
    'treatment',
    'include_pending_redemptions',
    'other_itemized_deductions',
    'capital_loss_used_est',
    'dependents_count',
    'children_under_17_count',
    'apply_oregon_kicker',
    'or40_2024_line24_total_tax_before_credits',
    'redemptions_received_usd',
    'redemptions_pending_usd',
    'purchases_total_usd',
    'gross_income_used_usd',
    'agi_used_usd',
    'federal_deduction_method_used',
    'federal_deduction_used_usd',
    'federal_taxable_income_usd',
    'federal_tax_before_credits_usd',
    'federal_credits_usd',
    'federal_tax_after_credits_usd',
    'federal_marginal_bracket_rate',
    'federal_effective_rate',
    'oregon_taxable_income_usd',
    'oregon_tax_before_credits_usd',
    'oregon_exemption_credit_usd',
    'oregon_kicker_credit_usd',
    'oregon_tax_owed_usd',
    'oregon_refund_credit_usd',
    'total_estimated_tax_liability_usd',
    'notes'
  ];

  function roundToCents(value) {
    if (value === null || value === undefined || value === '') return '';
    return Math.round(value * 100) / 100;
  }

  function fmtNum(value) {
    if (value === null || value === undefined || value === '') return '';
    return roundToCents(value).toString();
  }

  function fmtBool(value) {
    return value ? 'true' : 'false';
  }

  function fmtRate(value) {
    if (value === null || value === undefined || value === '') return '';
    return (value * 100).toFixed(2) + '%';
  }

  function escapeCSV(value) {
    if (value === null || value === undefined) return '';
    const str = String(value);
    if (str.includes(',') || str.includes('"') || str.includes('\n')) {
      return '"' + str.replace(/"/g, '""') + '"';
    }
    return str;
  }

  function buildTaxSummaryCsvRow(summary) {
    const { selections, inputs, result } = summary;
    const isOregon = selections.state === 'OR';

    const row = [
      selections.taxYear || 2025,
      new Date().toISOString(),
      APP_VERSION,
      'true',
      selections.filingStatus || 'single',
      selections.state || 'OR',
      selections.treatment || 'sweepstakes',
      fmtBool(selections.includePending),
      fmtNum(selections.otherItemizedDeductions || 0),
      fmtNum(selections.capitalLossUsed || 0),
      (selections.dependents || 0).toString(),
      (selections.childrenUnder17 || 0).toString(),
      fmtBool(selections.applyKicker),
      isOregon ? fmtNum(selections.or40Line24 || 0) : '',
      fmtNum(inputs.redemptionsReceived),
      fmtNum(inputs.redemptionsPending),
      fmtNum(inputs.purchasesTotal),
      fmtNum(result.grossIncome),
      fmtNum(result.agi),
      result.federal.deductionMethod || 'standard',
      fmtNum(result.federal.deductionUsed),
      fmtNum(result.federal.taxableIncome),
      fmtNum(result.federal.federalTax),
      fmtNum(result.federalCredits ? result.federalCredits.nonrefundableCreditsApplied : 0),
      fmtNum(result.federalCredits ? result.federalCredits.federalTaxAfterCredits : result.federal.federalTax),
      fmtRate(result.federal.marginalBracket),
      fmtRate(result.federal.effectiveRate),
      isOregon ? fmtNum(result.oregon.taxableIncome) : '',
      isOregon ? fmtNum(result.oregon.taxBeforeCredits) : '',
      isOregon ? fmtNum(result.oregon.exemptionCredit) : '',
      isOregon ? fmtNum(result.oregon.kickerCredit) : '',
      isOregon ? fmtNum(result.oregon.taxOwed) : '',
      isOregon ? fmtNum(result.oregon.refundCredit) : '',
      fmtNum(result.totalTaxLiability),
      'Estimate only. Not a tax form.'
    ];

    const commentLines = [
      '# Informational estimate only. Not a tax form. Not for filing.',
      '# Generated by Sweepsites Tracker. Verify with official forms and tax software.'
    ];

    const headerLine = CSV_HEADERS.map(escapeCSV).join(',');
    const dataLine = row.map(escapeCSV).join(',');
    const csv = commentLines.join('\n') + '\n' + headerLine + '\n' + dataLine + '\n';

    return { headers: CSV_HEADERS, row, csv };
  }

  function getTaxSummaryCsvFilename(taxYear) {
    const today = new Date().toISOString().split('T')[0];
    return `tax_estimate_summary_${taxYear}_${today}.csv`;
  }

  return {
    buildTaxSummaryCsvRow,
    getTaxSummaryCsvFilename,
    CSV_HEADERS,
    APP_VERSION,
    fmtNum,
    fmtBool,
    fmtRate,
    escapeCSV,
    roundToCents
  };
})();

// Import TaxEngine for building test result
const TaxEngine = require('../tax/engine.js');

let passed = 0;
let failed = 0;

function test(name, fn) {
  try {
    fn();
    console.log('✓', name);
    passed++;
  } catch (e) {
    console.log('✗', name);
    console.log('  Error:', e.message);
    failed++;
  }
}

function assertEqual(actual, expected, message = '') {
  if (actual !== expected) {
    throw new Error(`Expected "${expected}", got "${actual}". ${message}`);
  }
}

function assertClose(actual, expected, tolerance = 0.01, message = '') {
  if (Math.abs(actual - expected) > tolerance) {
    throw new Error(`Expected ${expected} ± ${tolerance}, got ${actual}. ${message}`);
  }
}

function assertContains(str, substr, message = '') {
  if (!str.includes(substr)) {
    throw new Error(`Expected string to contain "${substr}". ${message}`);
  }
}

console.log('\n========================================');
console.log('CSV Builder Unit Tests');
console.log('========================================\n');

// =============================================================================
// Build test data using the sample values from the requirements
// =============================================================================

const testSelections = {
  taxYear: 2025,
  filingStatus: 'single',
  state: 'OR',
  treatment: 'sweepstakes',
  includePending: false,
  otherItemizedDeductions: 0,
  capitalLossUsed: 3000,
  dependents: 0,
  childrenUnder17: 0,
  applyKicker: true,
  or40Line24: 3702.00
};

const testInputs = {
  redemptionsReceived: 42227.69,
  redemptionsPending: 696.20,
  purchasesTotal: 27408.83
};

// Calculate using TaxEngine
const testDomain = {
  redemptionsReceived: testInputs.redemptionsReceived,
  redemptionsPending: testInputs.redemptionsPending,
  purchasesTotal: testInputs.purchasesTotal,
  includePending: testSelections.includePending,
  treatment: testSelections.treatment,
  otherItemizedDeductions: 0
};

const testResult = TaxEngine.calcCombinedFromDomain({
  taxYear: 2025,
  filingStatus: testSelections.filingStatus,
  domain: testDomain,
  capitalLossUsed: testSelections.capitalLossUsed,
  applyKicker: testSelections.applyKicker,
  or40Line24: testSelections.or40Line24
});

const testSummary = {
  selections: testSelections,
  inputs: testInputs,
  result: testResult
};

// =============================================================================
// Test: Headers match exactly
// =============================================================================

console.log('CSV Header Tests');

test('Headers count is 35', () => {
  assertEqual(CsvBuilder.CSV_HEADERS.length, 35);
});

test('First header is tax_year', () => {
  assertEqual(CsvBuilder.CSV_HEADERS[0], 'tax_year');
});

test('Last header is notes', () => {
  assertEqual(CsvBuilder.CSV_HEADERS[34], 'notes');
});

test('informational_only header exists at position 3', () => {
  assertEqual(CsvBuilder.CSV_HEADERS[3], 'informational_only');
});

// =============================================================================
// Test: Row values match expected
// =============================================================================

console.log('\nRow Value Tests (Sample Data)');

const csvOutput = CsvBuilder.buildTaxSummaryCsvRow(testSummary);

test('Row has same length as headers', () => {
  assertEqual(csvOutput.row.length, csvOutput.headers.length);
});

test('tax_year = 2025', () => {
  assertEqual(csvOutput.row[0], 2025);
});

test('informational_only = true', () => {
  assertEqual(csvOutput.row[3], 'true');
});

test('filing_status = single', () => {
  assertEqual(csvOutput.row[4], 'single');
});

test('state = OR', () => {
  assertEqual(csvOutput.row[5], 'OR');
});

test('treatment = sweepstakes', () => {
  assertEqual(csvOutput.row[6], 'sweepstakes');
});

test('include_pending_redemptions = false', () => {
  assertEqual(csvOutput.row[7], 'false');
});

test('capital_loss_used_est = 3000', () => {
  assertEqual(csvOutput.row[9], '3000');
});

test('apply_oregon_kicker = true', () => {
  assertEqual(csvOutput.row[12], 'true');
});

test('or40_line24 = 3702', () => {
  assertEqual(csvOutput.row[13], '3702');
});

test('redemptions_received_usd = 42227.69', () => {
  assertEqual(csvOutput.row[14], '42227.69');
});

test('redemptions_pending_usd = 696.2', () => {
  // 696.20 may be formatted as 696.2
  assertEqual(parseFloat(csvOutput.row[15]), 696.2);
});

test('purchases_total_usd = 27408.83', () => {
  assertEqual(csvOutput.row[16], '27408.83');
});

test('gross_income_used_usd = 42227.69 (no pending included)', () => {
  assertEqual(csvOutput.row[17], '42227.69');
});

// AGI = gross - cap loss = 42227.69 - 3000 = 39227.69
test('agi_used_usd = 39227.69', () => {
  assertEqual(csvOutput.row[18], '39227.69');
});

test('federal_deduction_method_used = standard', () => {
  assertEqual(csvOutput.row[19], 'standard');
});

// =============================================================================
// Test: Oregon kicker credit
// =============================================================================

console.log('\nOregon Kicker Tests');

// Kicker = 3702 * 0.09863 = 365.13 (approx)
test('oregon_kicker_credit_usd ≈ 365.13', () => {
  const kickerValue = parseFloat(csvOutput.row[30]);
  assertClose(kickerValue, 365.13, 0.01);
});

test('Oregon fields are populated (state=OR)', () => {
  // oregon_taxable_income_usd should not be empty
  if (csvOutput.row[27] === '') {
    throw new Error('Oregon taxable income should not be empty for state=OR');
  }
});

// =============================================================================
// Test: CSV string format
// =============================================================================

console.log('\nCSV String Format Tests');

test('CSV starts with comment lines', () => {
  assertContains(csvOutput.csv, '# Informational estimate only. Not a tax form. Not for filing.');
});

test('CSV contains disclaimer in notes', () => {
  assertContains(csvOutput.csv, 'Estimate only. Not a tax form.');
});

test('CSV contains header line', () => {
  assertContains(csvOutput.csv, 'tax_year,generated_at_iso,app_version');
});

test('CSV ends with newline', () => {
  if (!csvOutput.csv.endsWith('\n')) {
    throw new Error('CSV should end with newline');
  }
});

// =============================================================================
// Test: Filename format
// =============================================================================

console.log('\nFilename Tests');

test('Filename contains tax year', () => {
  const filename = CsvBuilder.getTaxSummaryCsvFilename(2025);
  assertContains(filename, '2025');
});

test('Filename ends with .csv', () => {
  const filename = CsvBuilder.getTaxSummaryCsvFilename(2025);
  if (!filename.endsWith('.csv')) {
    throw new Error('Filename should end with .csv');
  }
});

test('Filename contains date in YYYY-MM-DD format', () => {
  const filename = CsvBuilder.getTaxSummaryCsvFilename(2025);
  const today = new Date().toISOString().split('T')[0];
  assertContains(filename, today);
});

test('Filename format is correct', () => {
  const filename = CsvBuilder.getTaxSummaryCsvFilename(2025);
  const today = new Date().toISOString().split('T')[0];
  assertEqual(filename, `tax_estimate_summary_2025_${today}.csv`);
});

// =============================================================================
// Test: Helper functions
// =============================================================================

console.log('\nHelper Function Tests');

test('fmtNum rounds to cents', () => {
  assertEqual(CsvBuilder.fmtNum(123.456), '123.46');
});

test('fmtNum handles null', () => {
  assertEqual(CsvBuilder.fmtNum(null), '');
});

test('fmtBool formats true', () => {
  assertEqual(CsvBuilder.fmtBool(true), 'true');
});

test('fmtBool formats false', () => {
  assertEqual(CsvBuilder.fmtBool(false), 'false');
});

test('fmtRate formats percentage', () => {
  assertEqual(CsvBuilder.fmtRate(0.12), '12.00%');
});

test('escapeCSV handles commas', () => {
  assertEqual(CsvBuilder.escapeCSV('hello, world'), '"hello, world"');
});

test('escapeCSV handles quotes', () => {
  assertEqual(CsvBuilder.escapeCSV('say "hello"'), '"say ""hello"""');
});

// =============================================================================
// Test: Non-Oregon state (empty Oregon fields)
// =============================================================================

console.log('\nNon-Oregon State Tests');

test('Oregon fields empty when state != OR', () => {
  const nonOrSummary = {
    selections: { ...testSelections, state: 'CA' },
    inputs: testInputs,
    result: testResult
  };

  const nonOrCsv = CsvBuilder.buildTaxSummaryCsvRow(nonOrSummary);

  // oregon_taxable_income_usd should be empty
  assertEqual(nonOrCsv.row[27], '', 'Oregon taxable income should be empty for non-OR state');
  // or40_line24 should be empty
  assertEqual(nonOrCsv.row[13], '', 'OR-40 line 24 should be empty for non-OR state');
});

// =============================================================================
// Summary
// =============================================================================

console.log('\n========================================');
console.log(`Results: ${passed} passed, ${failed} failed`);
console.log('========================================\n');

if (failed > 0) {
  process.exit(1);
}
console.log('All tests passed!');
